spring:
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka-streams-one:
  orders-topic: orders_topic
  orders-pattern-one-topic: order_pattern_one_topic
  orders-pattern-one-topic-replicas: 1
  orders-pattern-one-topic-partitions: 1
  orders-reward-one-topic: order_reward_one_topic
  orders-reward-one-topic-replicas: 1
  orders-reward-one-topic-partitions: 1
  orders-storage-one-topic: order_storage_one_topic
  orders-storage-one-topic-replicas: 1
  orders-storage-one-topic-partitions: 1
