spring:
  kafka:
    listener:
      missing-topics-fatal: false
kafka-feedback-streams:
  feedback-topic: feedback_topic
  feedback-good-topic: feedback_good_topic
  feedback-good-topic-replicas: 1
  feedback-good-topic-partitions: 1
