spring:
  kafka:
    listener:
      missing-topics-fatal: false
kafka-hopping-window-inventory-stream:
  inventory-topic: inventory_topic
  inventory-timestamp-topic: inventory_hopping_window_topic
  inventory-timestamp-topic-partitions: 1
  inventory-timestamp-topic-replicas: 1

