spring:
  kafka:
    listener:
      missing-topics-fatal: false
kafka-feedback-two-streams:
  feedback-topic: feedback_topic
  feedback-two-good-topic: feedback_two_good_topic
  feedback-two-good-topic-replicas: 1
  feedback-two-good-topic-partitions: 1
  feedback-two-bad-topic: feedback_two_bad_topic
  feedback-two-bad-topic-replicas: 1
  feedback-two-bad-topic-partitions: 1
