server:
  port: 9001
  servlet:
    context-path: /kafka-orders
kafka-order-producer:
  orders-topic: orders_topic
  orders-topic-replicas: 1
  orders-topic-partitions: 1
  orders-reply-to-topic: orders_reply_to_topic
  orders-reply-to-topic-replicas: 1
  orders-reply-to-topic-partitions: 1
  promotions-topic: promotions_topic
  promotions-topic-replicas: 1
  promotions-topic-partitions: 1
  discounts-topic: discounts_topic
  discounts-topic-replicas: 1
  discounts-topic-partitions: 1
  feedback-topic: feedback_topic
  feedback-topic-replicas: 1
  feedback-topic-partitions: 1
  flash-sale-votes-topic: flash_sale_votes_topic
  flash-sale-votes-topic-replicas: 1
  flash-sale-votes-topic-partitions: 1
  inventory-topic: inventory_topic
  inventory-topic-replicas: 1
  inventory-topic-partitions: 1
  online-order-topic: online_order_topic
  online-order-topic-replicas: 1
  online-order-topic-partitions: 1
  online-payment-topic: online_payment_topic
  online-payment-topic-replicas: 1
  online-payment-topic-partitions: 1
spring:
  datasource:
    url: jdbc:h2:mem:orders
    username: george
    password: orwell
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: kafka-orders-cg
      enable-auto-commit: true
      auto-offset-reset: earliest
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.kat.ordersmodel